### ISSUE TITLE
Valgrind

### ISSUE THREAD

**Issue by jacobmerson** [SCOREC/rhel7-dev#4]
A valgrind install/module would be useful.

**Comment by wrtobin** [comment]
Working on this but the lack of gfortran in the default rhel7 GCC install is holding up the install since we want this available without requiring you to load a non-default compiler module (gcc 4.8.5 or gcc 7.3.0) prior to loading the valgrind module.

**Comment by jacobmerson** [comment]
From my perspective this isn't urgent...I have my own copy compiled.

**Comment by cwsmith** [comment]
There is a valgrind install in `/usr/bin` on pachisi.

```
cwsmith@pachisi: ~ $ which valgrind
/usr/bin/valgrind
cwsmith@pachisi: ~ $ valgrind --version
valgrind-3.13.0
```

Which is the latest version spack provides (outside 'develop'):

```
$ spack info valgrind
...
Preferred version:
    3.13.0     https://sourceware.org/pub/valgrind/valgrind-3.13.0.tar.bz2

Safe versions:
    develop    [git] git://sourceware.org/git/valgrind.git
    3.13.0     https://sourceware.org/pub/valgrind/valgrind-3.13.0.tar.bz2
    3.12.0     https://sourceware.org/pub/valgrind/valgrind-3.12.0.tar.bz2
    3.11.0     https://sourceware.org/pub/valgrind/valgrind-3.11.0.tar.bz2
    3.10.1     https://sourceware.org/pub/valgrind/valgrind-3.10.1.tar.bz2
    3.10.0     https://sourceware.org/pub/valgrind/valgrind-3.10.0.tar.bz2
...
```

**Comment by wrtobin** [comment]
not seeing /usr/bin/valgrind on Jenga

**Comment by cwsmith** [comment]
OK.  I emailed help@ and Cc'd you.

**Comment by jacobmerson** [comment]
Not sure if the scorec help email address is working properly...A couple weeks ago I emailed Bob at that address and the ticket never went through. The new ticketing system seems to work.

**Comment by cwsmith** [comment]
help@ installed valgrind 3.13.0 on the rhel7 systems.

```
cwsmith@jenga: ~ $ which valgrind
/usr/bin/valgrind
cwsmith@jenga: ~ $ valgrind --version
valgrind-3.13.0
```

If there are systems with missing installs please reopen this ticket.
