### ISSUE TITLE
GDB missing some system debug symbols

### ISSUE THREAD

**Issue by jacobmerson** [SCOREC/rhel7-dev#5]
When using gdb I get the follwoing error message. I think this is just a package that needs to get installed in the red hat package manager.
`Missing separate debuginfos, use: debuginfo-install glibc-2.17-222.el7.x86_64`

**Comment by cwsmith** [comment]
gdb 8.1 is now available via a top level module:

```
$ module av gdb
-----/opt/scorec/spack/lmod/linux-rhel7-x86_64/Core-------
   gdb/8.1-yeit6hu
```

Please reopen this issue if there are any problems with it.
